services:
  inference:
    container_name: inference-arb
    env_file:
      - .env
    build: .
    command: python -u /app/app.py
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://inference:8002/inference/${TOKEN}"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - ./inference-data:/app/data
  
  updater:
    container_name: updater-arb
    build: .
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8002
    command: >
      sh -c "
      while true; do
        python -u /app/update_app.py;
        sleep 24h;
      done
      "
    depends_on:
      inference:
        condition: service_healthy

  worker:
    container_name: worker-arb
    image: alloranetwork/allora-offchain-node:latest
    volumes:
      - ./worker-data:/data
    depends_on:
      inference:
        condition: service_healthy
    env_file:
      - ./worker-data/env_file

volumes:
  inference-data:
  worker-data:
